// temp-angular/src/app/components/resume-builder/resume-builder.ts
// ─────────────────────────────────────────────────────────────────────────────
// ResumeBuilder (orchestrator / smart component)
//
// Responsibilities:
//   • Loads or creates the Resume record via ResumeService
//   • Loads the section records via SectionService, maps them to ResumeData
//   • Saves the resume metadata + all sections on "Save"
//   • Loads the selected template via TemplateService
//   • Generates the sanitised live-preview HTML (delegates to pure utils)
//   • Delegates ALL rendering to child components
// ─────────────────────────────────────────────────────────────────────────────

import { Component, OnInit, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { forkJoin, of } from 'rxjs';
import { catchError, switchMap } from 'rxjs/operators';

import { TemplateService } from '../../service/template.service';
import { ResumeService, ResumeDTO } from '../../service/resume.service';
import { SectionService, ResumeSection, SectionType } from '../../service/section.service';
import { Template } from '../../core/models/template.model';

import {
  ResumeData,
  ExperienceItem,
  EducationItem,
  ProjectItem,
  SectionItem,
  ResumeMeta,
} from './models/resume.model';

import {
  DEFAULT_RESUME_DATA,
  BUILDER_SECTIONS,
  TEMPLATE_ACCENT_PALETTE,
} from './utils/resume-defaults';

import {
  buildUniversalPreviewHtml,
  buildTemplatePreviewHtml,
} from './utils/preview-html.builder';

import { BuilderTopbarComponent } from './components/builder-topbar/builder-topbar';
import { SectionNavComponent } from './components/section-nav/section-nav';
import { FormPanelComponent } from './components/form-panel/form-panel';
import { PreviewPanelComponent } from './components/preview-panel/preview-panel';

// ── Helper: map sectionType enum → local section key ────────────────────────
const SECTION_TYPE_TO_KEY: Record<SectionType, string> = {
  PERSONAL:       'personal',
  EXPERIENCE:     'experience',
  EDUCATION:      'education',
  SKILLS:         'skills',
  PROJECTS:       'projects',
  CERTIFICATIONS: 'summary',
};

@Component({
  selector: 'app-resume-builder',
  standalone: true,
  imports: [
    CommonModule,
    BuilderTopbarComponent,
    SectionNavComponent,
    FormPanelComponent,
    PreviewPanelComponent,
  ],
  templateUrl: './resume-builder.html',
  styleUrl: './resume-builder.css',
})
export class ResumeBuilder implements OnInit {
  // ── State ──────────────────────────────────────────────────────────────────
  readonly activeSection = signal<string>('personal');
  readonly templateId    = signal<number>(1);
  readonly isLoading     = signal<boolean>(false);
  readonly saveStatus    = signal<'idle' | 'saving' | 'saved' | 'error'>('idle');

  selectedTemplate = signal<Template | null>(null);
  resume: ResumeData = structuredClone(DEFAULT_RESUME_DATA);

  /** API persistence metadata */
  private meta: ResumeMeta = { resumeId: null, sectionIds: {} };

  /** Monotonically increasing id counter for new list entries */
  private nextId = 100;

  // ── Static data (passed down to child components) ─────────────────────────
  readonly sections: SectionItem[] = BUILDER_SECTIONS;

  // ── DI ─────────────────────────────────────────────────────────────────────
  constructor(
    private readonly route:           ActivatedRoute,
    private readonly router:          Router,
    private readonly templateService: TemplateService,
    private readonly resumeService:   ResumeService,
    private readonly sectionService:  SectionService,
    private readonly sanitizer:       DomSanitizer,
  ) {}

  // ── Lifecycle ──────────────────────────────────────────────────────────────
  ngOnInit(): void {
    console.log('🚀 ResumeBuilder initialized ');
    this.route.queryParams.subscribe(params => {
      const tid = params['templateId'] ? +params['templateId'] : 1;
      const rid = params['resumeId']   ? +params['resumeId']   : null;

      this.templateId.set(tid);

      // Load template
      this.templateService.getTemplateById(tid).subscribe(t => {
        this.selectedTemplate.set(t ?? null);
      });

      // Load existing resume data from API if resumeId is provided
      if (rid) {
        this.loadResumeFromApi(rid);
      }
    });
  }

  // ── API load ───────────────────────────────────────────────────────────────
  private loadResumeFromApi(resumeId: number): void {
  this.isLoading.set(true);

  forkJoin({
    resume: this.resumeService.getById(resumeId).pipe(catchError(() => of(null))),
    sections: this.sectionService.getByResume(resumeId).pipe(catchError(() => of([]))),
  }).subscribe(({ resume, sections }) => {
    this.isLoading.set(false);

    if (!resume) return;

    this.meta.resumeId = resume.resumeId ?? null;

    // ✅ Start with fresh base
    let updatedResume: ResumeData = {
      ...structuredClone(DEFAULT_RESUME_DATA),
      fullName: resume.title ?? DEFAULT_RESUME_DATA.fullName,
      jobTitle: resume.targetJobTitle ?? DEFAULT_RESUME_DATA.jobTitle,
    };

    console.log('✅ Sections Loaded:', sections);

    for (const section of sections) {
      const key = SECTION_TYPE_TO_KEY[section.sectionType];

      const sid = section.id ?? section.sectionId;
      if (sid && key) {
        this.meta.sectionIds[key] = sid;
      }

      // ✅ Merge section into temp object
      updatedResume = this.mergeSection(updatedResume, section);
    }

    // ✅ Single assignment → ensures UI refresh
    this.resume = { ...updatedResume };

    console.log('✅ Final Resume State:', this.resume);
  });
}

  /** Merges one persisted section's content into the local ResumeData */
  private mergeSection(
    current: ResumeData,
    section: ResumeSection
  ): ResumeData {

    // ✅ Handle both stringified JSON & object
    let c: any = section.content;

    if (!c) return current;

    if (typeof c === 'string') {
      try {
        c = JSON.parse(c);
      } catch (err) {
        console.error('❌ Failed to parse section content:', c);
        return current;
      }
    }

    switch (section.sectionType) {

      // ───────────────── PERSONAL ─────────────────
      case 'PERSONAL':
        return {
          ...current,
          fullName: c.fullName ?? current.fullName,
          jobTitle: c.jobTitle ?? current.jobTitle,
          email:    c.email    ?? current.email,
          phone:    c.phone    ?? current.phone,
          location: c.location ?? current.location,
          website:  c.website  ?? current.website,
          linkedin: c.linkedin ?? current.linkedin,
          summary:  c.summary  ?? current.summary,
        };

      // ───────────────── EXPERIENCE ─────────────────
      case 'EXPERIENCE':
        return {
          ...current,
          experience: Array.isArray(c.items)
            ? c.items.map((e: any, i: number) => ({
                id: e.id ?? this.nextId++,
                company: e.company ?? '',
                role: e.role ?? '',
                startDate: e.startDate ?? '',
                endDate: e.endDate ?? '',
                current: e.current ?? false,
                description: e.description ?? '',
              }))
            : current.experience,
        };

      // ───────────────── EDUCATION ─────────────────
      case 'EDUCATION':
        return {
          ...current,
          education: Array.isArray(c.items)
            ? c.items.map((e: any) => ({
                id: e.id ?? this.nextId++,
                institution: e.institution ?? '',
                degree: e.degree ?? '',
                field: e.field ?? '',
                year: e.year ?? '',
              }))
            : current.education,
        };

      // ───────────────── PROJECTS ─────────────────
      case 'PROJECTS':
        return {
          ...current,
          projects: Array.isArray(c.items)
            ? c.items.map((p: any) => ({
                id: p.id ?? this.nextId++,
                name: p.name ?? '',
                role: p.role ?? '',
                url: p.url ?? '',
                startDate: p.startDate ?? '',
                endDate: p.endDate ?? '',
                description: p.description ?? '',
              }))
            : current.projects,
        };

      // ───────────────── SKILLS ─────────────────
      case 'SKILLS':
        return {
          ...current,
          skills: Array.isArray(c.items)
            ? c.items.filter((s: any) => typeof s === 'string')
            : current.skills,
        };

      // ───────────────── DEFAULT ─────────────────
      default:
        console.warn('⚠️ Unknown section type:', section.sectionType);
        return current;
    }
  }

  // ── Derived: accent colour ─────────────────────────────────────────────────
  get accentColor(): string {
    return (
      this.selectedTemplate()?.cssStyles?.match(/--accent:\s*(#[0-9a-fA-F]{3,8})/)?.[1] ??
      TEMPLATE_ACCENT_PALETTE[this.templateId()] ??
      '#6366f1'
    );
  }

  // ── Derived: raw HTML string (used for PDF export) ────────────────────────
  private get rawResumeHtml(): string {
    const template = this.selectedTemplate();
    return template?.htmlLayout
      ? buildTemplatePreviewHtml(
          template.htmlLayout,
          template.cssStyles ?? '',
          this.resume,
        )
      : buildUniversalPreviewHtml(this.resume, this.accentColor);
  }

  // ── Derived: sanitised live-preview HTML ───────────────────────────────────
  get livePreviewHtml(): SafeHtml {
    return this.sanitizer.bypassSecurityTrustHtml(this.rawResumeHtml);
  }

  // ── Section navigation ─────────────────────────────────────────────────────
  onSectionChanged(sectionId: string): void {
    this.activeSection.set(sectionId);
  }

  // ── AI patch (from toolbar modals: tailor / translate) ────────────────────
  onResumePatched(patch: Partial<ResumeData>): void {
    this.resume = { ...this.resume, ...patch };
  }

  // ── Experience handlers ────────────────────────────────────────────────────
  onAddExperience(): void {
    const blank: ExperienceItem = {
      id: this.nextId++,
      company: '', role: '',
      startDate: '', endDate: '',
      current: false, description: '',
    };
    this.resume = { ...this.resume, experience: [...this.resume.experience, blank] };
  }

  onRemoveExperience(id: number): void {
    this.resume = {
      ...this.resume,
      experience: this.resume.experience.filter(e => e.id !== id),
    };
  }

  // ── Education handlers ─────────────────────────────────────────────────────
  onAddEducation(): void {
    const blank: EducationItem = {
      id: this.nextId++,
      institution: '', degree: '', field: '', year: '',
    };
    this.resume = { ...this.resume, education: [...this.resume.education, blank] };
  }

  onRemoveEducation(id: number): void {
    this.resume = {
      ...this.resume,
      education: this.resume.education.filter(e => e.id !== id),
    };
  }

  // ── Project handlers ───────────────────────────────────────────────────────
  onAddProject(): void {
    const blank: ProjectItem = {
      id: this.nextId++,
      name: '', role: '', url: '',
      startDate: '', endDate: '', description: '',
    };
    this.resume = { ...this.resume, projects: [...this.resume.projects, blank] };
  }

  onRemoveProject(id: number): void {
    this.resume = {
      ...this.resume,
      projects: this.resume.projects.filter(p => p.id !== id),
    };
  }

  // ── Skills handlers ────────────────────────────────────────────────────────
  onAddSkill(skill: string): void {
    const trimmed = skill.trim();
    if (trimmed && !this.resume.skills.includes(trimmed)) {
      this.resume = { ...this.resume, skills: [...this.resume.skills, trimmed] };
    }
  }

  onRemoveSkill(skill: string): void {
    this.resume = {
      ...this.resume,
      skills: this.resume.skills.filter(s => s !== skill),
    };
  }

  // ── Top-level actions ──────────────────────────────────────────────────────
  onBack(): void {
    this.router.navigate(['/dashboard']);
  }

  onExportPdf(): void {
    const resumeHtml = this.rawResumeHtml;
    const fullName   = (this.resume.fullName || 'resume').replace(/\s+/g, '_');

    const printWindow = window.open('', '_blank', 'width=900,height=700');
    if (!printWindow) {
      alert('Popup blocked — please allow popups for this site and try again.');
      return;
    }

    printWindow.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${fullName}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    html, body { background: #fff; }
    @page {
      size: A4;
      margin: 0;
    }
    @media print {
      html, body { width: 210mm; }
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
  </style>
</head>
<body>${resumeHtml}</body>
</html>`);

    printWindow.document.close();

    // Wait for resources (fonts, images) then print
    printWindow.onload = () => {
      printWindow.focus();
      printWindow.print();
      printWindow.close();
    };
  }

  /**
   * Persist the resume and its sections to the backend.
   *
   * Flow:
   *  1. Create or update the Resume record.
   *  2. Build sections from local ResumeData and bulk-upsert them.
   *  3. Show a brief "Saved!" indicator and update the URL with the resumeId.
   */
  onSave(): void {
    this.saveStatus.set('saving');
    const userId = this.getCurrentUserId();

    const resumeDTO: ResumeDTO = {
      ...(this.meta.resumeId ? { id: this.meta.resumeId } : {}),
      userId,
      title:          this.resume.fullName || 'My Resume',
      targetJobTitle: this.resume.jobTitle,
      templateId:     this.templateId(),
      status:         'DRAFT',
      language:       'en',
    };

    const resumeOp$ = this.meta.resumeId
      ? this.resumeService.update(this.meta.resumeId, resumeDTO)
      : this.resumeService.create(resumeDTO);

    resumeOp$.pipe(
      catchError(err => {
        console.error('Resume save failed', err);
        this.saveStatus.set('error');
        return of(null);
      }),
      switchMap(saved => {
        if (!saved) return of(null);

        const resumeId = saved.resumeId;

        // Guard: backend must return a valid id before saving sections
        if (!resumeId) {
          console.error('Resume save succeeded but returned no id', saved);
          this.saveStatus.set('error');
          return of(null);
        }

        this.meta.resumeId = resumeId;

        // Reflect new resumeId in URL without re-triggering navigation
        this.router.navigate([], {
          relativeTo:          this.route,
          queryParams:         { resumeId, templateId: this.templateId() },
          queryParamsHandling: 'merge',
          replaceUrl:          true,
        });

        const sectionPayloads = this.buildSectionPayloads(resumeId);
        return this.sectionService.bulkUpdate(resumeId, sectionPayloads).pipe(
          catchError(err => {
            console.error('Sections save failed', err);
            this.saveStatus.set('error');
            return of(null);
          })
        );
      })
    ).subscribe(result => {
      if (result !== null) {
        this.saveStatus.set('saved');
        setTimeout(() => this.saveStatus.set('idle'), 2000);
      }
    });
  }

  // ── Private helpers ────────────────────────────────────────────────────────

  private getCurrentUserId(): number {
    try {
      const user = JSON.parse(localStorage.getItem('user') ?? '{}');
      return user?.id ?? 1;
    } catch {
      return 1;
    }
  }

  /**
   * Converts the local ResumeData into the flat list of ResumeSection payloads
   * that the bulk-update endpoint expects.
   */
  private buildSectionPayloads(resumeId: number): ResumeSection[] {
    const base = (type: SectionType, order: number): Partial<ResumeSection> => ({
      ...(this.meta.sectionIds[SECTION_TYPE_TO_KEY[type]]
        ? { sectionId: this.meta.sectionIds[SECTION_TYPE_TO_KEY[type]] }
        : {}),
      resumeId,
      sectionType:  type,
      isVisible:    true,
      displayOrder: order,
    });

    return [
      {
        ...(base('PERSONAL', 0) as ResumeSection),
        title:   'Personal Information',
        content: {
          fullName: this.resume.fullName,
          jobTitle: this.resume.jobTitle,
          email:    this.resume.email,
          phone:    this.resume.phone,
          location: this.resume.location,
          website:  this.resume.website,
          linkedin: this.resume.linkedin,
          summary:  this.resume.summary,
        },
      },
      {
        ...(base('EXPERIENCE', 1) as ResumeSection),
        title:   'Experience',
        content: { items: this.resume.experience },
      },
      {
        ...(base('EDUCATION', 2) as ResumeSection),
        title:   'Education',
        content: { items: this.resume.education },
      },
      {
        ...(base('PROJECTS', 3) as ResumeSection),
        title:   'Projects',
        content: { items: this.resume.projects },
      },
      {
        ...(base('SKILLS', 4) as ResumeSection),
        title:   'Skills',
        content: { items: this.resume.skills },
      },
    ];
  }
}

// src/pages/ResumeBuilder/ResumeBuilder.jsx
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import templateService from '../../services/templateService';
import resumeService from '../../services/resumeService';
import sectionService from '../../services/sectionService';
import { 
  DEFAULT_RESUME_DATA, 
  BUILDER_SECTIONS, 
  TEMPLATE_ACCENT_PALETTE 
} from './utils/resumeDefaults';
import { 
  buildUniversalPreviewHtml, 
  buildTemplatePreviewHtml 
} from './utils/previewHtmlBuilder';

// Components
import BuilderTopbar from './components/BuilderTopbar';
import SectionNav from './components/SectionNav';
import FormPanel from './components/FormPanel';
import PreviewPanel from './components/PreviewPanel';

import './ResumeBuilder.css';

const SECTION_TYPE_TO_KEY = {
  PERSONAL:       'personal',
  EXPERIENCE:     'experience',
  EDUCATION:      'education',
  SKILLS:         'skills',
  PROJECTS:       'projects',
  CERTIFICATIONS: 'summary', // Based on original code mapping
};

const ResumeBuilder = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const navigate = useNavigate();

  const [activeSection, setActiveSection] = useState('personal');
  const [templateId, setTemplateId] = useState(1);
  const [isLoading, setIsLoading] = useState(false);
  const [saveStatus, setSaveStatus] = useState('idle');
  const [selectedTemplate, setSelectedTemplate] = useState(null);
  const [resume, setResume] = useState(structuredClone(DEFAULT_RESUME_DATA));
  const [meta, setMeta] = useState({ resumeId: null, sectionIds: {} });
  const [nextId, setNextId] = useState(100);

  const tid = parseInt(searchParams.get('templateId') || '1');
  const rid = searchParams.get('resumeId') ? parseInt(searchParams.get('resumeId')) : null;

  // ── Helpers ──────────────────────────────────────────────────────────────

  const mergeSection = useCallback((current, section) => {
    let content = section.content;
    if (!content) return current;

    if (typeof content === 'string') {
      try {
        content = JSON.parse(content);
      } catch (err) {
        console.error('Failed to parse section content:', content);
        return current;
      }
    }

    switch (section.sectionName) {
      case 'PERSONAL':
        return {
          ...current,
          fullName: content.fullName ?? current.fullName,
          jobTitle: content.jobTitle ?? current.jobTitle,
          email:    content.email    ?? current.email,
          phone:    content.phone    ?? current.phone,
          location: content.location ?? current.location,
          website:  content.website  ?? current.website,
          linkedin: content.linkedin ?? current.linkedin,
          summary:  content.summary  ?? current.summary,
        };
      case 'EXPERIENCE':
        return {
          ...current,
          experience: Array.isArray(content.items)
            ? content.items.map((e) => ({
                id: e.id ?? Math.random(),
                company: e.company ?? '',
                role: e.role ?? '',
                startDate: e.startDate ?? '',
                endDate: e.endDate ?? '',
                current: e.current ?? false,
                description: e.description ?? '',
              }))
            : current.experience,
        };
      case 'EDUCATION':
        return {
          ...current,
          education: Array.isArray(content.items)
            ? content.items.map((e) => ({
                id: e.id ?? Math.random(),
                institution: e.institution ?? '',
                degree: e.degree ?? '',
                field: e.field ?? '',
                year: e.year ?? '',
              }))
            : current.education,
        };
      case 'PROJECTS':
        return {
          ...current,
          projects: Array.isArray(content.items)
            ? content.items.map((p) => ({
                id: p.id ?? Math.random(),
                name: p.name ?? '',
                role: p.role ?? '',
                url: p.url ?? '',
                startDate: p.startDate ?? '',
                endDate: p.endDate ?? '',
                description: p.description ?? '',
              }))
            : current.projects,
        };
      case 'SKILLS':
        return {
          ...current,
          skills: Array.isArray(content.items)
            ? content.items.filter((s) => typeof s === 'string')
            : current.skills,
        };
      default:
        return current;
    }
  }, []);

  const loadResumeFromApi = useCallback(async (resumeId) => {
    setIsLoading(true);
    try {
      const [resumeDto, sections] = await Promise.all([
        resumeService.getById(resumeId),
        sectionService.getByResume(resumeId)
      ]);

      if (resumeDto) {
        const sectionIds = {};
        let updatedResume = {
          ...structuredClone(DEFAULT_RESUME_DATA),
          fullName: resumeDto.title ?? DEFAULT_RESUME_DATA.fullName,
          jobTitle: resumeDto.targetJobTitle ?? DEFAULT_RESUME_DATA.jobTitle,
        };

        for (const section of sections) {
          const key = SECTION_TYPE_TO_KEY[section.sectionName];
          const sid = section.id;
          if (sid && key) {
            sectionIds[key] = sid;
          }
          updatedResume = mergeSection(updatedResume, section);
        }

        setResume(updatedResume);
        setMeta({ resumeId: resumeDto.resumeId, sectionIds });
      }
    } catch (err) {
      console.error('Failed to load resume:', err);
    } finally {
      setIsLoading(false);
    }
  }, [mergeSection]);


  // ── Derived State ────────────────────────────────────────────────────────

  const accentColor = useMemo(() => {
    return (
      selectedTemplate?.cssStyles?.match(/--accent:\s*(#[0-9a-fA-F]{3,8})/)?.[1] ??
      TEMPLATE_ACCENT_PALETTE[templateId] ??
      '#6366f1'
    );
  }, [selectedTemplate, templateId]);

  const rawResumeHtml = useMemo(() => {
    return selectedTemplate?.htmlLayout
      ? buildTemplatePreviewHtml(
          selectedTemplate.htmlLayout,
          selectedTemplate.cssStyles ?? '',
          resume
        )
      : buildUniversalPreviewHtml(resume, accentColor);
  }, [selectedTemplate, resume, accentColor]);

  const handleExportPdf = useCallback(() => {
    const fullName = (resume.fullName || 'resume').replace(/\s+/g, '_');
    const printWindow = window.open('', '_blank', 'width=900,height=700');
    if (!printWindow) {
      alert('Popup blocked — please allow popups for this site and try again.');
      return;
    }

    printWindow.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${fullName}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    html, body { background: #fff; }
    @page { size: A4; margin: 0; }
    @media print {
      html, body { width: 210mm; }
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
  </style>
</head>
<body>${rawResumeHtml}</body>
</html>`);

    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.focus();
      printWindow.print();
      printWindow.close();
    };
  }, [resume.fullName, rawResumeHtml]);

  // ── Effects ──────────────────────────────────────────────────────────────

  useEffect(() => {
    setTemplateId(tid);
    const fetchTemplate = async () => {
      const t = await templateService.getTemplateById(tid);
      setSelectedTemplate(t);
    };
    fetchTemplate();

    if (rid) {
      loadResumeFromApi(rid);
    }
  }, [tid, rid, loadResumeFromApi]);

  useEffect(() => {
    if (searchParams.get('export') === 'pdf' && !isLoading && rawResumeHtml && selectedTemplate) {
      const timer = setTimeout(() => {
        handleExportPdf();
        setSearchParams((prev) => {
          prev.delete('export');
          return prev;
        }, { replace: true });
      }, 1000);
      return () => clearTimeout(timer);
    }
  }, [isLoading, rawResumeHtml, selectedTemplate, searchParams, setSearchParams, handleExportPdf]);


  // ── Handlers ─────────────────────────────────────────────────────────────

  const handleResumeUpdate = (patch) => {
    setResume(prev => ({ ...prev, ...patch }));
  };

  const handleSave = async () => {
    setSaveStatus('saving');
    try {
      const user = JSON.parse(localStorage.getItem('user') ?? '{}');
      const userId = user?.userId ?? user?.id;

      const resumeDto = {
        ...(meta.resumeId ? { id: meta.resumeId } : {}),
        userId,
        title: resume.fullName || 'My Resume',
        templateId: templateId,
        templateName: selectedTemplate?.name || 'Default Template',
        templateCategory: selectedTemplate?.category || 'General',
        summary: resume.summary || '',
        resumeContent: JSON.stringify(resume),
        status: 'DRAFT',
      };

      const saved = meta.resumeId
        ? await resumeService.update(meta.resumeId, resumeDto)
        : await resumeService.create(resumeDto);

      if (saved && saved.id) {
        setMeta(prev => ({ ...prev, resumeId: saved.id }));

        // Update URL
        setSearchParams({ resumeId: saved.id, templateId });

        const sectionPayloads = [
          {
            sectionId: meta.sectionIds.personal,
            sectionName: 'PERSONAL',
            content: {
              fullName: resume.fullName,
              jobTitle: resume.jobTitle,
              email:    resume.email,
              phone:    resume.phone,
              location: resume.location,
              website:  resume.website,
              linkedin: resume.linkedin,
              summary:  resume.summary,
            },
            displayOrder: 0
          },
          {
            sectionId: meta.sectionIds.experience,
            sectionName: 'EXPERIENCE',
            content: { items: resume.experience },
            displayOrder: 1
          },
          {
            sectionId: meta.sectionIds.education,
            sectionName: 'EDUCATION',
            content: { items: resume.education },
            displayOrder: 2
          },
          {
            sectionId: meta.sectionIds.projects,
            sectionName: 'PROJECTS',
            content: { items: resume.projects },
            displayOrder: 3
          },
          {
            sectionId: meta.sectionIds.skills,
            sectionName: 'SKILLS',
            content: { items: resume.skills },
            displayOrder: 4
          }
        ];

        try {
          const savedSections = await sectionService.upsertAll(saved.id, sectionPayloads);
          
          // Update meta with new section IDs
          const newSectionIds = { ...meta.sectionIds };
          savedSections.forEach(ss => {
            if (ss && ss.id && ss.sectionName) {
              const key = SECTION_TYPE_TO_KEY[ss.sectionName];
              if (key) newSectionIds[key] = ss.id;
            }
          });
          setMeta(prev => ({ ...prev, sectionIds: newSectionIds }));
        } catch (sectionErr) {
          console.warn('Sections save failed (resume itself saved OK):', sectionErr);
        }

        setSaveStatus('saved');
        setTimeout(() => setSaveStatus('idle'), 2000);
      } else {
        // saved is null/undefined — still unblock the button
        setSaveStatus('idle');
      }
    } catch (err) {
      console.error('Save failed:', err);
      setSaveStatus('error');
      setTimeout(() => setSaveStatus('idle'), 3000);
    }
  };




  const handleAddExperience = () => {
    const blank = {
      id: nextId,
      company: '', role: '',
      startDate: '', endDate: '',
      current: false, description: '',
    };
    setNextId(n => n + 1);
    setResume(prev => ({ ...prev, experience: [...prev.experience, blank] }));
  };

  const handleRemoveExperience = (id) => {
    setResume(prev => ({
      ...prev,
      experience: prev.experience.filter(e => e.id !== id)
    }));
  };

  const handleAddEducation = () => {
    const blank = {
      id: nextId,
      institution: '', degree: '', field: '', year: '',
    };
    setNextId(n => n + 1);
    setResume(prev => ({ ...prev, education: [...prev.education, blank] }));
  };

  const handleRemoveEducation = (id) => {
    setResume(prev => ({
      ...prev,
      education: prev.education.filter(e => e.id !== id)
    }));
  };

  const handleAddProject = () => {
    const blank = {
      id: nextId,
      name: '', role: '', url: '',
      startDate: '', endDate: '', description: '',
    };
    setNextId(n => n + 1);
    setResume(prev => ({ ...prev, projects: [...prev.projects, blank] }));
  };

  const handleRemoveProject = (id) => {
    setResume(prev => ({
      ...prev,
      projects: prev.projects.filter(p => p.id !== id)
    }));
  };

  const handleAddSkill = (skill) => {
    const trimmed = skill.trim();
    if (trimmed && !resume.skills.includes(trimmed)) {
      setResume(prev => ({ ...prev, skills: [...prev.skills, trimmed] }));
    }
  };

  const handleRemoveSkill = (skill) => {
    setResume(prev => ({
      ...prev,
      skills: prev.skills.filter(s => s !== skill)
    }));
  };

  return (
    <div className="builder-shell">
      <BuilderTopbar
        accentColor={accentColor}
        saveStatus={saveStatus}
        isLoading={isLoading}
        resume={resume}
        onBack={() => navigate('/dashboard')}
        onExportPdf={handleExportPdf}
        onSave={handleSave}
        onPatch={handleResumeUpdate}
      />

      <div className="builder-body">
        <SectionNav
          sections={BUILDER_SECTIONS}
          activeSection={activeSection}
          selectedTemplate={selectedTemplate}
          templateId={templateId}
          accentColor={accentColor}
          onSectionChange={setActiveSection}
        />

        <FormPanel
          resume={resume}
          activeSection={activeSection}
          accentColor={accentColor}
          onUpdate={handleResumeUpdate}
          onAddExperience={handleAddExperience}
          onRemoveExperience={handleRemoveExperience}
          onAddEducation={handleAddEducation}
          onRemoveEducation={handleRemoveEducation}
          onAddProject={handleAddProject}
          onRemoveProject={handleRemoveProject}
          onAddSkill={handleAddSkill}
          onRemoveSkill={handleRemoveSkill}
        />

        <PreviewPanel
          previewHtml={rawResumeHtml}
          onExportPdf={handleExportPdf}
        />
      </div>
    </div>
  );
};

export default ResumeBuilder;
